image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - name: docker:dind

stages:
  - build
  - test
  # - deploy

before_script:
  - docker info
  - apt-get install npm && npm install
  - npm run build --prod
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

docker-build:
  stage: build
  script:
    - cd angularVersion
    - docker build . -t registry.gitlab.com/mrfoofums/fk:latest
    - docker push registry.gitlab.com/mrfoofums/fk:latest

run-tests:
  stage: test
  tags:
    - docker
  script:
    - echo 'testing my pipeline yay'

